# Generated by Django 4.2.16 on 2026-01-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0002_busstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BusShiftStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Stop order in the shift')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled time at this stop')),
                ('bus_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.busshift')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.busstop')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('bus_shift', 'order'), ('bus_shift', 'bus_stop')},
            },
        ),
        migrations.AddField(
            model_name='busshift',
            name='stops',
            field=models.ManyToManyField(related_name='shifts', through='geography.BusShiftStop', to='geography.busstop'),
        ),
    ]
