# Generated by Django 4.2.16 on 2026-01-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_busshift_busshiftstop_busshift_stops'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('name', 'place')},
        ),
    ]
